[package]
name = "spacestorage"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "spacestorage"
path = "src/main.rs"

[dependencies]
spacestorage-config = { path = "../config" }
spacestorage-admin-proto = { path = "../admin-proto" }
spacestorage-migrate = { path = "../migrate" }
spacestorage-admin-ui = { path = "../admin-ui" }
spacestorage-ingest = { path = "../ingest" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }

[features]
default = []
migration-backup = ["spacestorage-migrate/migrate"]
complete-product = [
    "migration-backup",
    "spacestorage-admin-ui/ui",
    "spacestorage-ingest/ingest",
]

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
