[package]
name = "spacestorage-node"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["first-binary"]
first-binary = []
handlers-complete = [
    "dep:spacestorage-handler-cassandra",
    "dep:spacestorage-handler-elasticsearch",
    "dep:spacestorage-handler-clickhouse",
    "dep:spacestorage-handler-s3",
    "dep:spacestorage-handler-webdav",
]
migration-backup = [
    "spacestorage-config/migration-backup",
    "spacestorage-release-profile/migration-backup",
    "spacestorage-migrate/migrate",
]
complete-product = [
    "handlers-complete",
    "migration-backup",
    "spacestorage-config/complete-product",
    "spacestorage-release-profile/complete-product",
    "spacestorage-admin-ui/ui",
    "spacestorage-ingest/ingest",
]
[dependencies]
spacestorage-config = { path = "../config" }
spacestorage-admin-proto = { path = "../admin-proto" }
spacestorage-release-profile = { path = "../release-profile" }
spacestorage-storage = { path = "../storage" }
spacestorage-crypto = { path = "../crypto" }
spacestorage-types = { path = "../types" }
spacestorage-authz = { path = "../authz" }
spacestorage-membership = { path = "../membership" }
spacestorage-internode = { path = "../internode" }
spacestorage-replication = { path = "../replication" }
spacestorage-handler-postgresql = { path = "../handler-postgresql" }
spacestorage-handler-redis = { path = "../handler-redis" }
spacestorage-handler-cassandra = { path = "../handler-cassandra", optional = true }
spacestorage-handler-elasticsearch = { path = "../handler-elasticsearch", optional = true }
spacestorage-handler-clickhouse = { path = "../handler-clickhouse", optional = true }
spacestorage-handler-s3 = { path = "../handler-s3", optional = true }
spacestorage-handler-webdav = { path = "../handler-webdav", optional = true }
spacestorage-observability = { path = "../observability" }
spacestorage-migrate = { path = "../migrate" }
spacestorage-backup = { path = "../backup" }
spacestorage-admin-ui = { path = "../admin-ui" }
spacestorage-ingest = { path = "../ingest" }
tokio = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }
hyper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bytes = { workspace = true }
arc-swap = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
subtle = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
hyper-util = { version = "0.1", features = ["tokio"] }
tower = { workspace = true }
http-body-util = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros"] }
