limits {
    max_key 4KiB;
    max_value 32MiB;
    max_query_text 2MiB;
    max_result 128MiB;
    max_connections_per_entrypoint 20000;
    max_connections_per_principal 2000;
}
query {
    max_concurrent_per_node 1024;
    max_concurrent_per_namespace 256;
    max_memory 1GiB;
    spill on;
}
