[package]
name = "spacestoraged"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "spacestoraged"
path = "src/main.rs"

[features]
default = ["first-binary"]
first-binary = []
handlers-complete = ["spacestorage-node/handlers-complete"]
complete-product = [
    "handlers-complete",
    "spacestorage-node/complete-product",
]

[dependencies]
spacestorage-config = { path = "../config" }
spacestorage-node = { path = "../node" }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
